Algoritmo "Teste de Mesa Para 2"
// Disciplina   : Teste de Messa pra estrutura "para"
// Professor   :
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas da Silva Dantas
// Data atual  : 24/01/2023

Var
// Seção de Declarações das variáveis 

  x, y , i : inteiro

Inicio


   para i de 1 ate 4 faca
     y <- 1 - 1
     x <- 1 * 10
     escreva (i)
   fimpara

 


Fimalgoritmo