Algoritmo "Teste de Mesa Para "
// Disciplina   : Teste de Messa pra estrutura "para"
// Professor   :
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas da Silva Dantas
// Data atual  : 24/01/2023


Var
// Seção de Declarações das variáveis 

  x,y, i : Inteiro

Inicio

    x <- 4
    y <- x + 2

    para i de 1 ate x faca
      escreva (x, " " , y)
      y <- y + i
    fimpara




Fimalgoritmo