Algoritmo "Teste De Enquanto 5"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
// Seção de Declarações das variáveis 

   x,y : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   x <- 0
   y <- 0
   
   enquanto (x < 5) faca
      y <- x * 3
      escreva (y)
      x <- x + 1
   fimenquanto
   escrevaL
   escreval ("Fim")

Fimalgoritmo